version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${SQL_SA_PASSWORD}
    ports:
      - "21433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SQL_SA_PASSWORD} -Q 'select 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
  otel-collector:
    image: otel/opentelemetry-collector:0.116.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    command: ["--config", "/etc/otelcol/config.yaml"]
    ports:
      - "4317:4317"
  jaeger:
    image: jaegertracing/all-in-one:1.62
    ports:
      - "16686:16686"

  gateway:
    build:
      context: ..
      dockerfile: src/Gateway/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    depends_on:
      - ui
      - elsa
    ports:
      - "8080:8080"
  ui:
    build:
      context: ..
      dockerfile: src/Ui.BlazorServer/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    depends_on:
      - gateway
  elsa:
    build:
      context: ..
      dockerfile: src/Elsa.Server/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317

  arc:
    build:
      context: ..
      dockerfile: services/arc.api/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  dar:
    build:
      context: ..
      dockerfile: services/dar.api/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  dba:
    build:
      context: ..
      dockerfile: services/dba.api/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  bud:
    build:
      context: ..
      dockerfile: services/bud.api/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  ctr:
    build:
      context: ..
      dockerfile: services/ctr.api/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  cos:
    build:
      context: ..
      dockerfile: services/cos.api/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  rap:
    build:
      context: ..
      dockerfile: services/rap.api/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  rde:
    build:
      context: ..
      dockerfile: services/rde.api/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  rep:
    build:
      context: ..
      dockerfile: services/rep.api/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  rre:
    build:
      context: ..
      dockerfile: services/rre.api/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  rst:
    build:
      context: ..
      dockerfile: services/rst.api/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317

networks:
  default:
    name: microservices-boilerplate
